apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  api-key: {{ default "" .Values.container_auto_scan.lacework.api_access_key | b64enc | quote }}
  api-secret: {{ default "" .Values.container_auto_scan.lacework.api_access_secret | b64enc | quote }}