apiVersion: v2
name: lacework-container-auto-scan
description: A Helm chart for Kubernetes
type: application
version: 0.2.2
appVersion: "1.16.0"
dependencies:
  - name: proxy-scanner
    version: 0.2.10
    condition: proxy-scanner.enabled
    repository: https://lacework.github.io/helm-charts