name: "lacework-container-auto-scan"
nameOverride: "lacework-container-auto-scan"
fullnameOverride: "lacework-container-auto-scan"

container_auto_scan:
  lacework:
    account: "<<account>>"
    sub_account: "<<subaccount>>"
    api_access_key: "<<api_accses_key>>"
    api_access_secret: "<<api_secret_key>>"
  proxy_scanner_url: "http://proxy-scanner:8080"

proxy-scanner:
  fullnameOverride: lacework-proxy-scanner
  enabled: true
  config:
    default_registry: index.docker.io
    static_cache_location: /opt/lacework
    lacework:
      account_name: <<account>>
      integration_access_token: <<aaccess_token>>
    registries:
      - domain: index.docker.io
        name: Docker Hub
        ssl: true
        is_public: true
        auto_poll: false
        disable_non_os_package_scanning: false
      - domain: mcr.microsoft.com
        name: Microsoft Container Registry (MCR)
        ssl: true
        auth_header_name: NoAuth
        is_public: true
        auto_poll: false
        credentials:
        disable_non_os_package_scanning: false
      - domain: gcr.io
        name: Google Container Registry
        ssl: true
        is_public: true
        auth_header_name: NoAuth
        auto_poll: false
        disable_non_os_package_scanning: false
      - domain: k8s.gcr.io
        name: Kubernetes Container Registry
        ssl: true
        is_public: true
        auth_header_name: NoAuth
        auto_poll: false
        disable_non_os_package_scanning: false
      - domain: quay.io
        name: RedHat Quay.io
        ssl: true
        is_public: true
        auth_header_name: NoAuth
        auto_poll: false
        disable_non_os_package_scanning: false
    certs:
      skipCert: false
      serverCertificate:
      serverKey:

# # Default values for lacework-container-auto-scan.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.

# replicaCount: 1

# image:
#   repository: nginx
#   pullPolicy: IfNotPresent
#   # Overrides the image tag whose default is the chart appVersion.
#   tag: ""

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

# serviceAccount:
#   # Specifies whether a service account should be created
#   create: true
#   # Annotations to add to the service account
#   annotations: {}
#   # The name of the service account to use.
#   # If not set and create is true, a name is generated using the fullname template
#   name: ""

# podAnnotations: {}

# podSecurityContext: {}
#   # fsGroup: 2000

# securityContext: {}
#   # capabilities:
#   #   drop:
#   #   - ALL
#   # readOnlyRootFilesystem: true
#   # runAsNonRoot: true
#   # runAsUser: 1000

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

# resources: {}
#   # We usually recommend not to specify default resources and to leave this as a conscious
#   # choice for the user. This also increases chances charts run on environments with little
#   # resources, such as Minikube. If you do want to specify resources, uncomment the following
#   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   # limits:
#   #   cpu: 100m
#   #   memory: 128Mi
#   # requests:
#   #   cpu: 100m
#   #   memory: 128Mi

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
